openapi: 3.0.0
info:
  title: "Flask REST API For F2 Application"
  description: "An API about lists and tasks"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Task:
      type: "object"
      required:
        - name
      properties:
        _id:
          type: "string"
        name:
          type: "string"
        description:
          type: "string"
        priority:
          type: "integer"
        listId:
          type: "string"
        boardId:
          type: "string"
        creationTs:
          type: "integer"
  parameters:
    id:
      name: "_id"
      description: "The ID of the task to get"
      in: path
      required: True
      schema:
        type: "string"
    boardId:
      name: "boardId"
      description: "The ID of the board to get"
      in: path
      required: True
      schema:
        type: "string"
    listId:
      name: "listId"
      description: "The ID of the board to get"
      in: path
      required: True
      schema:
        type: "string"


paths:
  /board:
    get:
      operationId: "controller.board_controller.find_board"
      tags:
        - "Board"
      summary: "Read the board configuration"
      responses:
        "200":
          description: "Successfully read the board configuration"
  /board/{boardId}/tasks/{listId}:
    get:
      operationId: "controller.tasks_controller.find_tasks"
      tags:
        - "Tasks"
      summary: "Read all tasks"
      parameters:
        - $ref: "#/components/parameters/boardId"
        - $ref: "#/components/parameters/listId"
      responses:
        "200":
          description: "Successfully read all tasks"
    post:
      operationId: "controller.tasks_controller.create"
      tags:
        - Tasks
      summary: "Create a new task"
      parameters:
        - $ref: "#/components/parameters/boardId"
        - $ref: "#/components/parameters/listId"
      requestBody:
        x-body-name: "task"
        description: "Task to create"
        required: True
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
      responses:
        "201":
          description: "Successfully created a new task"
  /tasks/{_id}:
    delete:
      tags:
        - Tasks
      operationId: "controller.tasks_controller.delete"
      summary: "Delete a task"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "204":
          description: "Successfully deleted task"
    put:
      tags:
        - Tasks
      operationId: "controller.tasks_controller.update"
      summary: "Update a task"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: "Successfully updated task"
      requestBody:
        x-body-name: "task"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"