openapi: 3.0.0
info:
  title: "Flask REST API For F2 Application"
  description: "An API about lists and tasks"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Task:
      type: "object"
      required:
        - name
      properties:
        id:
          type: "string"
        name:
          type: "string"
        description:
          type: "string"
        priority:
          type: "integer"
        listId:
          type: "string"
        boardId:
          type: "string"
        date:
          type: "string"
  parameters:
    id:
      name: "id"
      description: "The ID of the task to get"
      in: path
      required: True
      schema:
        type: "string"
    boardIdPathParam:
      name: "board_id"
      description: "The ID of the board to get"
      in: path
      required: True
      schema:
        type: "string"
    boardIdQueryParam:
      name: "board_id"
      description: "The ID of the board to get"
      in: query
      required: True
      schema:
        type: "string"
    listId:
      name: "list_id"
      description: "The list ID of the regarding list"
      in: path
      required: True
      schema:
        type: "string"


paths:
  /board:
    get:
      operationId: "controller.board_controller.read_board"
      tags:
        - "Board"
      summary: "Read the board configuration"
      responses:
        "200":
          description: "Successfully read the board configuration"
  /board/{board_id}/tasks/{list_id}:
    get:
      operationId: "controller.tasks_controller.read_tasks"
      tags:
        - "Task"
      summary: "Read all tasks"
      parameters:
        - $ref: "#/components/parameters/boardIdPathParam"
        - $ref: "#/components/parameters/listId"
      responses:
        "200":
          description: "Successfully read tasks with filter"
    post:
      operationId: "controller.tasks_controller.create"
      tags:
        - "Task"
      summary: "Create a new task"
      parameters:
        - $ref: "#/components/parameters/boardIdPathParam"
        - $ref: "#/components/parameters/listId"
      requestBody:
        x-body-name: "task"
        description: "Task to create"
        required: True
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
      responses:
        "201":
          description: "Successfully created a new task"
  /tasks/{id}:
    delete:
      tags:
        - Task
      operationId: "controller.tasks_controller.delete"
      summary: "Delete a task"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "204":
          description: "Successfully deleted task"
    put:
      tags:
        - Tasks
      operationId: "controller.tasks_controller.update"
      summary: "Update a task"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: "Successfully updated task"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "task"



