openapi: 3.0.0
info:
  title: "Flask REST API For F2 Application"
  description: "An API about lists and tasks"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Task:
      type: "object"
      required:
        - id
        - name
      properties:
        id:
          type: "string"
        name:
          type: "string"
        description:
          type: "string"
        priorty:
          type: "integer"
        listId:
          type: "string"
  parameters:
    id:
      name: "id"
      description: "The ID of the task to get"
      in: path
      required: True
      schema:
        type: "string"


paths:
  /board:
    get:
      operationId: "board_client.read_board"
      tags:
        - "Board"
      summary: "Read the board configuration"
      responses:
        "200":
          description: "Successfully read the board configuration"
  /board/tasks:
    get:
      operationId: "tasks.read_tasks"
      tags:
        - "Tasks"
      summary: "Read all tasks"
      responses:
        "200":
          description: "Successfully read all tasks"
    post:
      operationId: "tasks.create"
      tags:
        - Tasks
      summary: "Create a new task"
      requestBody:
        description: "Task to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "task"
              $ref: "#/components/schemas/Task"
      responses:
        "201":
          description: "Successfully created a new task"
  /board/tasks/{id}:
    get:
      operationId: "tasks.read_one"
      tags:
        - Tasks
      summary: "Read one task"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: "Successfully read task"
    delete:
      tags:
        - Tasks
      operationId: "tasks.delete"
      summary: "Delete a task"
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "204":
          description: "Successfully deleted task"

